name: Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Instalacja zaleznosci bezpieczeństwa
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Skanowanie kodu (Bandit)
        run: bandit -r ./mysite
        
      - name: Skanowanie zaleznosci (Safety)
        run: safety check -r requirements.txt
